1. llegar (to arrive, to reach)
2. tratar (to try, to treat)
3. hablar (to speak, to talk)
4. dejar (to leave, to allow, to let)
5. pasar (to pass, to happen, to spend (time))
6. llevar (to carry, to take, to wear)
7. tomar (to take, to drink)
8. encontrar (to find, to encounter)
9. crear (to create)
10. evitar (to avoid, to prevent)
11. quedar (to stay, to remain, to be left)
12. realizar (to carry out, to perform, to achieve)
13. resultar (to result, to turn out)
14. buscar (to search, to look for)
15. entrar (to enter, to go in)
16. considerar (to consider)
17. señalar (to point out, to indicate)
18. presentar (to present, to introduce)
19. trabajar (to work)
20. lograr (to achieve, to manage to)
21. esperar (to wait, to hope, to expect)
22. afirmar (to affirm, to assert, to state)
23. preguntar (to ask)
24. ganar (to win, to earn, to gain)
25. llamar (to call, to name)
26. cambiar (to change)
27. significar (to mean, to signify)
28. gustar (to like, to be pleasing)
29. explicar (to explain)
30. alcanzar (to reach, to catch up, to achieve)
31. pagar (to pay)
32. mirar (to look at, to watch)
33. sacar (to take out, to remove)
34. asegurar (to assure, to secure, to ensure)
35. utilizar (to use, to utilize)
36. informar (to inform, to report)
37. necesitar (to need)
38. declarar (to declare, to state)
39. representar (to represent)
40. manifestar (to express, to show, to state)
41. olvidar (to forget)
42. acabar (to finish, to end)
43. anunciar (to announce)
44. aceptar (to accept)
45. indicar (to indicate, to point out)
46. ayudar (to help)
47. terminar (to finish, to end)
48. escuchar (to listen)
49. importar (to matter, to import)
50. mejorar (to improve, to get better)
51. comprar (to buy)
52. estudiar (to study)
53. desarrollar (to develop)
54. formar (to form, to shape)
55. sentar (to sit, to seat)
56. aplicar (to apply)
57. matar (to kill)
58. participar (to participate)
59. levantar (to lift, to raise)
60. actuar (to act, to perform)
61. abandonar (to abandon, to leave)
62. intentar (to try, to attempt)
63. continuar (to continue)
64. observar (to observe)
65. enfrentar (to face, to confront)
66. comprobar (to verify, to check, to confirm)
67. recuperar (to recover, to get back)
68. demostrar (to demonstrate, to show)
69. usar (to use)
70. aumentar (to increase, to raise)
71. comentar (to comment, to remark)
72. agregar (to add)
73. iniciar (to initiate, to start)
74. echar (to throw, to pour, to expel)
75. superar (to overcome, to surpass)
76. colocar (to place, to put)
77. tocar (to touch, to play (an instrument))
78. determinar (to determine, to establish)
79. interesar (to interest)
80. controlar (to control, to monitor)
81. faltar (to lack, to miss)
82. bajar (to go down, to lower, to download)
83. implicar (to imply, to involve)
84. expresar (to express)
85. ocupar (to occupy, to take up)
86. preparar (to prepare)
87. imaginar (to imagine)
88. desear (to wish, to desire)
89. quitar (to remove, to take away)
90. salvar (to save, to rescue)
91. afectar (to affect)
92. regresar (to return, to go back)
93. analizar (to analyze)
94. contestar (to answer, to reply)
95. entregar (to deliver, to hand over)
96. acercar (to bring closer, to approach)
97. visitar (to visit)
98. bastar (to be enough, to suffice)
99. eliminar (to eliminate, to remove)
100. destacar (to highlight, to emphasize)
101. celebrar (to celebrate)
102. retirar (to withdraw, to remove)
103. plantear (to propose, to suggest, to raise (an issue))
104. apoyar (to support, to back)
105. citar (to quote, to cite, to summon)
106. provocar (to provoke, to cause)
107. aprovechar (to take advantage of, to make the most of)
108. parar (to stop)
109. garantizar (to guarantee, to ensure)
110. efectuar (to carry out, to execute)
111. relacionar (to relate, to connect)
112. facilitar (to facilitate, to provide)
113. modificar (to modify, to change)
114. situar (to place, to locate)
115. identificar (to identify)
116. llorar (to cry)
117. ordenar (to order, to arrange)
118. obligar (to force, to oblige)
119. organizar (to organize)
120. escapar (to escape)
121. cortar (to cut)
122. confirmar (to confirm)
123. incorporar (to incorporate, to include)
124. enviar (to send)
125. publicar (to publish)
126. negociar (to negotiate)
127. adoptar (to adopt)
128. contemplar (to contemplate, to consider)
129. hallar (to find, to discover)
130. luchar (to fight, to struggle)
131. conservar (to preserve, to conserve)
132. acompañar (to accompany)
133. dedicar (to dedicate, to devote)
134. caminar (to walk)
135. reflejar (to reflect)
136. cantar (to sing)
137. interpretar (to interpret, to perform)
138. casar (to marry)
139. comunicar (to communicate)
140. estimar (to estimate, to appreciate)
141. aclarar (to clarify, to clear up)
142. soportar (to endure, to tolerate)
143. funcionar (to function, to work)
144. probar (to try, to test)
145. ocultar (to hide, to conceal)
146. lanzar (to throw, to launch)
147. justificar (to justify)
148. viajar (to travel)
149. ampliar (to expand, to enlarge)
150. fijar (to set, to fix)
151. solicitar (to request, to apply for)
152. apreciar (to appreciate, to value)
153. despertar (to wake up)
154. calificar (to grade, to qualify)
155. avanzar (to advance, to move forward)
156. caracterizar (to characterize)
157. gritar (to shout, to scream)
158. figurar (to appear, to figure)
159. guardar (to keep, to save)
160. separar (to separate)
161. transformar (to transform)
162. aprobar (to approve, to pass)
163. preocupar (to worry)
164. disfrutar (to enjoy)
165. basar (to base)
166. prestar (to lend)
167. juzgar (to judge)
168. respetar (to respect)
169. enseñar (to teach, to show)
170. integrar (to integrate)
171. durar (to last)
172. investigar (to investigate)
173. mencionar (to mention)
174. cruzar (to cross)
175. revelar (to reveal)
176. generar (to generate)
177. constar (to consist of, to be recorded)
178. manejar (to handle, to drive)
179. notar (to notice, to note)
180. tirar (to throw, to pull)
181. afrontar (to face, to confront)
182. trasladar (to transfer, to move)
183. solucionar (to solve)
184. denominar (to call, to name)
185. cobrar (to charge, to collect)
186. instalar (to install)
187. renunciar (to resign, to give up)
188. llenar (to fill)
189. elaborar (to develop, to elaborate)
190. firmar (to sign)
191. marchar (to march, to go)
192. nombrar (to name, to appoint)
193. incrementar (to increase)
194. emplear (to employ, to use)
195. apuntar (to aim, to point, to write down)
196. completar (to complete)
197. bailar (to dance)
198. subrayar (to underline, to emphasize)
199. cuidar (to take care of)
200. elevar (to raise, to elevate)
201. precisar (to specify, to need)
202. marcar (to mark, to dial, to score)
203. votar (to vote)
204. gobernar (to govern, to rule)
205. proporcionar (to provide, to supply)
206. acusar (to accuse, to charge)
207. sumar (to add, to amount to)
208. abordar (to board, to tackle, to approach)
209. finalizar (to finish, to end)
210. detectar (to detect, to spot)
211. adaptar (to adapt, to adjust)
212. mandar (to send, to command)
213. destinar (to assign, to allocate, to send)
214. revisar (to review, to check, to revise)
215. consultar (to consult, to check with)
216. sonar (to sound, to ring)
217. asesinar (to murder, to assassinate)
218. aportar (to contribute, to provide)
219. evaluar (to evaluate, to assess)
220. rechazar (to reject, to turn down)
221. rodear (to surround, to encircle)
222. pronunciar (to pronounce, to declare)
223. denunciar (to report, to denounce)
224. acordar (to agree, to remember)
225. fumar (to smoke)
226. exclamar (to exclaim, to shout)
227. averiguar (to find out, to inquire)
228. saltar (to jump, to leap)
229. montar (to ride, to mount, to assemble)
230. condenar (to condemn, to convict)
231. registrar (to record, to register, to search)
232. comparar (to compare)
233. respectar (nonstandard verb — see ‘respetar’)
234. limpiar (to clean)
235. alejar (to move away, to distance)
236. arreglar (to fix, to arrange)
237. lavar (to wash)
238. titular (to title, to headline)
239. enterar (to find out, to inform — often used reflexively)
240. atravesar (to cross, to go through)
241. practicar (to practice)
242. ejecutar (to execute, to carry out)
243. colaborar (to collaborate, to contribute)
244. dominar (to dominate, to master)
245. reforzar (to reinforce, to strengthen)
246. limitar (to limit, to restrict)
247. amar (to love)
248. financiar (to finance, to fund)
249. liberar (to free, to liberate)
250. frenar (to brake, to slow down, to stop)
251. atacar (to attack)
252. otorgar (to grant, to award)
253. valorar (to value, to assess)
254. descansar (to rest, to relax)
255. ingresar (to enter, to join, to deposit)
256. cenar (to have dinner)
257. captar (to capture, to grasp)
258. recomendar (to recommend, to advise)
259. operar (to operate)
260. volar (to fly)
261. reiterar (to reiterate, to repeat)
262. curar (to heal, to cure)
263. impulsar (to promote, to boost, to propel)
264. opinar (to give an opinion, to think)
265. cocinar (to cook)
266. generalizar (to generalize)
267. radicar (to lie in, to be rooted in — often used with ‘en’)
268. saludar (to greet, to salute)
269. consolidar (to consolidate, to strengthen)
270. causar (to cause)
271. pintar (to paint)
272. examinar (to examine, to inspect)
273. variar (to vary, to change)
274. calcular (to calculate, to estimate)
275. invitar (to invite)
276. picar (to sting, to bite, to chop, to snack on)
277. respirar (to breathe)
278. convocar (to convene, to call, to summon)
279. mezclar (to mix)
280. concretar (to specify, to settle, to materialize)
281. jurar (to swear, to take an oath)
282. abarcar (to cover, to span, to include)
283. engañar (to deceive, to trick, to cheat)
284. arrancar (to start up, to pull out, to tear off)
285. adelantar (to advance, to overtake, to bring forward)
286. concentrar (to concentrate, to focus)
287. ubicar (to locate, to place)
288. reclamar (to claim, to demand, to complain)
289. formular (to formulate, to pose (a question))
290. conformar (to make up, to form, to comply)
291. estimular (to stimulate, to encourage)
292. penetrar (to penetrate, to go into)
293. preservar (to preserve, to protect)
294. confesar (to confess, to admit)
295. fabricar (to manufacture, to make)
296. robar (to steal, to rob)
297. besar (to kiss)
298. aguantar (to endure, to tolerate, to hold on)
299. seleccionar (to select, to choose)
300. alimentar (to feed, to nourish)
301. cansar (to tire, to get tired)
302. acostar (to lay down, to put to bed)
303. desplazar (to move, to displace)
304. fomentar (to encourage, to promote)
305. alterar (to alter, to upset)
306. conquistar (to conquer, to win over)
307. encargar (to put in charge, to order)
308. cargar (to load, to charge)
309. disparar (to shoot, to fire)
310. borrar (to erase, to delete)
311. pegar (to hit, to stick, to glue)
312. amenazar (to threaten)
313. inventar (to invent, to make up)
314. dudar (to doubt)
315. callar (to be quiet, to silence)
316. pasear (to stroll, to take a walk)
317. soltar (to let go, to release)
318. confiar (to trust, to confide)
319. tardar (to delay, to take time)
320. rescatar (to rescue, to recover)
321. orientar (to guide, to orient)
322. reflexionar (to reflect, to think over)
323. administrar (to manage, to administer)
324. derivar (to derive, to result in)
325. golpear (to hit, to strike)
326. vincular (to link, to connect)
327. ignorar (to ignore, to not know)
328. girar (to turn, to spin)
329. especializar (to specialize)
330. disimular (to hide, to conceal)
331. regular (to regulate, to control)
332. diferenciar (to differentiate, to distinguish)
333. renovar (to renew, to renovate)
334. fundar (to found, to establish)
335. compensar (to compensate, to make up for)
336. localizar (to locate, to find)
337. reaccionar (to react)
338. clasificar (to classify, to sort)
339. perdonar (to forgive, to pardon)
340. apartar (to move away, to separate)
341. soñar (to dream)
342. gozar (to enjoy)
343. designar (to designate, to appoint)
344. profundizar (to deepen, to go deeper into)
345. quemar (to burn)
346. criticar (to criticize)
347. reparar (to repair, to fix)
348. desempeñar (to perform, to carry out)
349. explotar (to exploit, to explode)
350. brindar (to offer, to give, to toast)
351. aspirar (to aspire, to vacuum)
352. conllevar (to entail, to involve)
353. sospechar (to suspect)
354. arrastrar (to drag, to pull)
355. originar (to originate, to cause)
356. prolongar (to prolong, to extend)
357. conversar (to converse, to talk)
358. descartar (to discard, to rule out)
359. gastar (to spend, to waste)
360. ajustar (to adjust, to tighten)
361. replicar (to reply, to replicate)
362. aliviar (to relieve, to ease)
363. contratar (to hire, to contract)
364. forzar (to force)
365. proyectar (to project, to plan)
366. anotar (to note down, to score)
367. centrar (to focus, to center)
368. adivinar (to guess, to predict)
369. verificar (to verify, to check)
370. optar (to choose, to opt)
371. procurar (to try, to make sure)
372. pesar (to weigh, to regret)
373. dotar (to equip, to provide)
374. estallar (to burst, to explode)
375. molestar (to bother, to annoy)
376. inaugurar (to inaugurate, to open)
377. vigilar (to watch, to guard)
378. rodar (to roll, to shoot a film)
379. entrevistar (to interview)
380. vengar (to avenge)
381. pelear (to fight, to argue)
382. librar (to free, to fight)
383. secar (to dry)
384. encerrar (to lock up, to enclose)
385. involucrar (to involve)
386. derrotar (to defeat)
387. armar (to arm, to assemble)
388. cesar (to cease, to stop)
389. encabezar (to lead, to head)
390. resaltar (to highlight, to emphasize)
391. protestar (to protest)
392. beneficiar (to benefit)
393. acelerar (to accelerate, to speed up)
394. constatar (to confirm, to verify)
395. conectar (to connect)
396. presionar (to press, to pressure)
397. avisar (to warn, to inform)
398. asomar (to appear, to peek out)
399. transportar (to transport, to carry)
400. expulsar (to expel, to kick out)
401. rallar (to grate)
402. experimentar (to experience, to experiment)
403. imitar (to imitate)
404. grabar (to record, to engrave)
405. tapar (to cover)
406. comportar (to entail, to involve)
407. murmurar (to murmur, to whisper)
408. alzar (to raise, to lift)
409. potenciar (to strengthen, to promote)
410. extrañar (to miss, to surprise)
411. calmar (to calm)
412. puntualizar (to specify, to point out)
413. enfriar (to cool down)
414. castigar (to punish)
415. ahorrar (to save (money, time))
416. apagar (to turn off, to extinguish)
417. combinar (to combine)
418. disputar (to dispute, to contest)
419. calentar (to heat)
420. circular (to circulate)
421. arrojar (to throw, to fling)
422. regalar (to give (a gift))
423. restar (to subtract, to diminish)
424. acomodar (to accommodate, to arrange)
425. diseñar (to design)
426. encantar (to love, to enchant)
427. secuestrar (to kidnap)
428. abrazar (to hug, to embrace)
429. industrializar (to industrialize)
430. narrar (to narrate, to tell)
431. explorar (to explore)
432. relatar (to recount, to tell)
433. reformar (to reform)
434. enterrar (to bury)
435. velar (to watch over, to stay awake)
436. coordinar (to coordinate)
437. cultivar (to cultivate)
438. sembrar (to sow, to plant)
439. tragar (to swallow)
440. aproximar (to bring closer, to approach)
441. contrarrestar (to counteract)
442. aconsejar (to advise)
443. multiplicar (to multiply)
444. acariciar (to caress)
445. abundar (to abound, to be abundant)
446. asociar (to associate)
447. bañar (to bathe)
448. pisar (to step on)
449. ratificar (to ratify)
450. habitar (to inhabit)
451. quejar (to complain)
452. reemplazar (to replace)
453. triunfar (to triumph, to succeed)
454. oscilar (to oscillate, to swing)
455. dictar (to dictate)
456. encarar (to confront, to face)
457. desviar (to divert, to deviate)
458. agarrar (to grab)
459. dialogar (to converse, to dialogue)
460. propiciar (to foster, to promote)
461. cazar (to hunt)
462. estrenar (to debut, to use for the first time)
463. acumular (to accumulate)
464. sentenciar (to sentence, to declare)
465. depositar (to deposit)
466. equivocar (to make a mistake)
467. arriesgar (to risk)
468. rezar (to pray)
469. inclinar (to tilt, to lean)
470. admirar (to admire)
471. ligar (to tie, to flirt)
472. paliar (to alleviate, to ease)
473. iluminar (to illuminate, to light up)
474. conciliar (to reconcile)
475. recalcar (to emphasize, to stress)
476. animar (to encourage, to cheer up)
477. lamentar (to regret, to lament)
478. reanudar (to resume)
479. agrupar (to group, to gather)
480. presenciar (to witness, to be present at)
481. tranquilizar (to reassure, to calm down)
482. educar (to educate, to raise)
483. rebajar (to reduce, to lower)
484. aislar (to isolate)
485. dibujar (to draw)
486. motivar (to motivate)
487. trazar (to trace, to draw)
488. sobrar (to be left over)
489. entrenar (to train)
490. tornar (to become, to turn)
491. sacrificar (to sacrifice)
492. colgar (to hang)
493. manipular (to manipulate)
494. asustar (to scare, to frighten)
495. violar (to violate, to rape)
496. apretar (to press, to tighten)
497. fallar (to fail)
498. reposar (to rest)
499. implantar (to implant, to establish)
500. atar (to tie)
501. juntar (to join)
502. adecuar (to adapt)
503. datar (to date)
504. anular (to cancel)
505. contrastar (to contrast)
506. enamorar (to make someone fall in love)
507. temblar (to tremble)
508. agotar (to exhaust)
509. doblar (to fold)
510. recobrar (to recover)
511. almorzar (to have lunch)
512. rogar (to beg)
513. autorizar (to authorize)
514. empujar (to push)
515. culminar (to culminate)
516. flotar (to float)
517. redactar (to draft)
518. enfatizar (to emphasize)
519. demandar (to demand)
520. acostumbrar (to get used to)
521. retrasar (to delay)
522. asimilar (to assimilate)
523. remontar (to overcome)
524. dañar (to damage)
525. descifrar (to decipher)
526. articular (to articulate)
527. perjudicar (to harm)
528. alegar (to allege)
529. estribar (to be based on)
530. movilizar (to mobilize)
531. evidenciar (to evidence)
532. cuestionar (to question)
533. reservar (to reserve)
534. aguardar (to await)
535. restaurar (to restore)
536. proclamar (to proclaim)
537. sujetar (to hold)
538. accionar (to activate)
539. cancelar (to cancel)
540. refugiar (to shelter)
541. felicitar (to congratulate)
542. retornar (to return)
543. ilustrar (to illustrate)
544. derribar (to knock down)
545. liquidar (to liquidate)
546. torear (to bullfight)
547. configurar (to configure)
548. aseverar (to assert)
549. guiar (to guide)
550. capturar (to capture)
551. dificultar (to hinder)
552. condicionar (to condition)
553. tolerar (to tolerate)
554. predominar (to predominate)
555. almacenar (to store)
556. acentuar (to accentuate)
557. erradicar (to eradicate)
558. arbitrar (to arbitrate)
559. programar (to schedule)
560. nadar (to swim)
561. sustentar (to sustain)
562. intercambiar (to exchange)
563. burlar (to mock)
564. indagar (to inquire)
565. infectar (to infect)
566. arrebatar (to snatch)
567. suministrar (to supply)
568. interrogar (to interrogate)
569. atrapar (to catch)
570. consolar (to comfort)
571. pescar (to fish)
572. suscitar (to provoke)
573. navegar (to sail)
574. argumentar (to argue)
575. exportar (to export)
576. editar (to edit)
577. complicar (to complicate)
578. gestionar (to manage)
579. albergar (to shelter)
580. despejar (to clear)
581. modernizar (to modernize)
582. inspirar (to inspire)
583. evocar (to evoke)
584. copiar (to copy)
585. procesar (to process)
586. desatar (to untie)
587. remediar (to remedy)
588. alegrar (to cheer up)
589. pactar (to agree)
590. retomar (to resume)
591. meditar (to meditate)
592. rectificar (to rectify)
593. quebrar (to break)
594. rellenar (to fill)
595. emocionar (to excite)
596. promocionar (to promote)
597. frustrar (to frustrate)
598. perfeccionar (to perfect)
599. brillar (to shine)
600. chocar (to crash)
601. ensayar (to rehearse)
602. ocasionar (to cause)
603. entrañar (to entail)
604. anticipar (to anticipate)
605. implementar (to implement)
606. apresurar (to hurry)
607. descargar (to unload/download)
608. fracasar (to fail)
609. asentar (to settle)
610. recrear (to recreate)
611. encarnar (to embody)
612. rematar (to finish off)
613. colar (to strain/filter)
614. neutralizar (to neutralize)
615. bloquear (to block)
616. traspasar (to transfer/pass through)
617. respaldar (to back/support)
618. susurrar (to whisper)
619. agitar (to shake)
620. plantar (to plant)
621. sancionar (to sanction)
622. insertar (to insert)
623. abonar (to pay/fertilize)
624. apoderar (to empower)
625. alternar (to alternate)
626. estrechar (to narrow)
627. minimizar (to minimize)
628. disfrazar (to disguise)
629. equilibrar (to balance)
630. hornear (to bake)
631. planear (to plan)
632. igualar (to equalize)
633. recortar (to trim)
634. ahogar (to drown)
635. recaudar (to collect/raise funds)
636. mediar (to mediate)
637. vaciar (to empty)
638. encarcelar (to imprison)
639. adjudicar (to award)
640. apostar (to bet)
641. reventar (to burst)
642. filmar (to film)
643. asignar (to assign)
644. ostentar (to hold/boast)
645. obrar (to act/work)
646. planificar (to plan)
647. reivindicar (to reclaim/demand)
648. paralizar (to paralyze)
649. orinar (to urinate)
650. despegar (to take off)
651. sintetizar (to synthesize)
652. afeitar (to shave)
653. canalizar (to channel)
654. desvelar (to reveal/stay awake)
655. especificar (to specify)
656. embarcar (to embark)
657. resucitar (to resurrect)
658. decretar (to decree)
659. deslizar (to slide)
660. encaminar (to direct/set on a path)
661. aplazar (to postpone)
662. apelar (to appeal)
663. odiar (to hate)
664. activar (to activate)
665. desencadenar (to unleash)
666. esforzar (to strive)
667. sobrepasar (to exceed)
668. fundamentar (to base/found)
669. complementar (to complement)
670. desplegar (to deploy/unfold)
671. alquilar (to rent)
672. posibilitar (to enable)
673. estirar (to stretch)
674. alentar (to encourage)
675. desayunar (to have breakfast)
676. transitar (to transit)
677. fotografiar (to photograph)
678. agravar (to worsen/aggravate)
679. reinar (to reign)
680. charlar (to chat)
681. festejar (to celebrate)
682. perpetuar (to perpetuate)
683. estrellar (to crash)
684. impresionar (to impress)
685. debilitar (to weaken)
686. suspirar (to sigh)
687. alargar (to lengthen)
688. desnudar (to undress)
689. congelar (to freeze)
690. protagonizar (to star/play the leading role)
691. clavar (to nail)
692. acertar (to get right)
693. poblar (to populate)
694. desembocar (to flow into/lead to)
695. lesionar (to injure)
696. regar (to water)
697. entablar (to initiate)
698. actualizar (to update)
699. unificar (to unify)
700. enfocar (to focus)
701. perfilar (to outline/profile)
702. instar (to urge)
703. ejercitar (to exercise)
704. reactivar (to reactivate)
705. plasmar (to express/embody)
706. privatizar (to privatize)
707. relajar (to relax)
708. rozar (to graze/touch lightly)
709. posar (to pose)
710. tostar (to toast)
711. percatar (to notice)
712. empeñar (to pawn)
713. vislumbrar (to glimpse)
714. evolucionar (to evolve)
715. rondar (to patrol/hover around)
716. internar (to intern/admit)
717. indignar (to outrage)
718. acarrear (to carry/lead to)
719. delimitar (to delimit)
720. volcar (to overturn)
721. precipitar (to hasten)
722. repasar (to review)
723. empatar (to tie/draw)
724. solventar (to solve)
725. aplastar (to crush)
726. fiar (to trust/sell on credit)
727. progresar (to progress)
728. traicionar (to betray)
729. consagrar (to consecrate)
730. intensificar (to intensify)
731. vomitar (to vomit)
732. confeccionar (to make/manufacture)
733. simbolizar (to symbolize)
734. sortear (to raffle/navigate)
735. matizar (to nuance/qualify)
736. desentrañar (to unravel)
737. diagnosticar (to diagnose)
738. despojar (to deprive/strip)
739. liderar (to lead)
740. acatar (to comply with)
741. reafirmar (to reaffirm)
742. postular (to nominate/apply)
743. reportar (to report)
744. atentar (to attempt/attack)
745. privar (to deprive)
746. acotar (to delimit/narrow down)
747. derrocar (to overthrow)
748. visualizar (to visualize)
749. contentar (to please/satisfy)
750. recabar (to gather/collect)
751. brotar (to sprout/emerge)
752. entusiasmar (to excite/enthuse)
753. estabilizar (to stabilize)
754. emigrar (to emigrate)
755. dilucidar (to clarify)
756. simplificar (to simplify)
757. asombrar (to amaze)
758. encajar (to fit)
759. afianzar (to strengthen)
760. reprochar (to reproach)
761. replantear (to reconsider)
762. desalojar (to evict)
763. tumbar (to knock down)
764. cooperar (to cooperate)
765. razonar (to reason)
766. aterrizar (to land)
767. devorar (to devour)
768. debutar (to debut)
769. exagerar (to exaggerate)
770. contactar (to contact)
771. resignar (to resign)
772. portar (to carry)
773. disipar (to dispel)
774. insultar (to insult)
775. enlazar (to link)
776. adornar (to decorate)
777. duplicar (to duplicate)
778. atajar (to intercept)
779. perpetrar (to perpetrate)
780. enmarcar (to frame)
781. formalizar (to formalize)
782. englobar (to encompass)
783. edificar (to build)
784. desmontar (to dismantle)
785. mojar (to wet)
786. conmemorar (to commemorate)
787. clarificar (to clarify)
788. agilizar (to expedite)
789. comercializar (to commercialize)
790. salvaguardar (to safeguard)
791. escalar (to climb)

List of ER Verbs
These verbs end in -ER and also follow a regular conjugation pattern.

792. deber (to owe, must, should)
793. parecer (to seem, appear)
794. conocer (to know, to meet)
795. perder (to lose)
796. aparecer (to appear, show up)
797. obtener (to obtain, get)
798. establecer (to establish)
799. creer (to believe)
800. comer (to eat)
801. ofrecer (to offer)
802. soler (to usually do, to tend to)
803. corresponder (to correspond)
804. reconocer (to recognize)
805. pretender (to intend, pretend, claim)
806. comprender (to understand)
807. defender (to defend)
808. responder (to respond, answer)
809. depender (to depend)
810. suceder (to happen, succeed/follow)
811. poseer (to possess, own)
812. vender (to sell)
813. meter (to put, insert)
814. correr (to run)
815. contener (to contain)
816. romper (to break)
817. nacer (to be born)
818. aprender (to learn)
819. atender (to attend to, assist)
820. imponer (to impose)
821. disponer (to arrange, dispose)
822. pertenecer (to belong)
823. recoger (to pick up, collect)
824. proteger (to protect)
825. beber (to drink)
826. convencer (to convince)
827. merecer (to deserve)
828. ejercer (to exercise, practice)
829. permanecer (to remain, stay)
830. tender (to tend, stretch out)
831. acceder (to access, agree)
832. desaparecer (to disappear)
833. promover (to promote)
834. vencer (to defeat, overcome)
835. crecer (to grow)
836. recorrer (to travel through, go across)
837. someter (to submit, subdue)
838. extender (to extend)
839. devolver (to return something)
840. carecer (to lack)
841. proceder (to proceed)
842. coger (to take, catch) *(use with caution, colloquial meaning varies by region)*
843. sorprender (to surprise)
844. componer (to compose, fix)
845. exponer (to expose, exhibit)
846. ceder (to yield, give in)
847. conceder (to grant, concede)
848. emprender (to undertake, start)
849. favorecer (to favor)
850. desprender (to detach, release)
851. equivaler (to be equivalent)
852. cometer (to commit)
853. suspender (to suspend, fail an exam)
854. fallecer (to pass away, die)
855. fortalecer (to strengthen)
856. doler (to hurt, ache)
857. esconder (to hide)
858. prometer (to promise)
859. escoger (to choose)
860. oponer (to oppose)
861. temer (to fear)
862. obedecer (to obey)
863. encender (to turn on, ignite)
864. padecer (to suffer, endure)
865. ascender (to ascend, promote)
866. desconocer (to not know, ignore)
867. agradecer (to thank, be grateful for)
868. envolver (to wrap, involve)
869. retener (to retain, hold back)
870. descender (to descend, go down)
871. comprometer (to compromise, commit)
872. acoger (to welcome, receive)
873. atrever (to dare)
874. cocer (to cook, boil)
875. restablecer (to restore, reestablish)
876. esclarecer (to clarify, shed light)
877. disolver (to dissolve)
878. absorber (to absorb)
879. joder (to annoy, bother) *(vulgar/slang, informal)*
880. retroceder (to go back, retreat)
881. enriquecer (to enrich)
882. entrever (to glimpse, suspect)
883. proveer (to provide, supply)
884. remover (to remove, stir)
885. acometer (to undertake, attack)
886. comparecer (to appear in court, attend formally)
887. apetecer (to crave, feel like)
888. acontecer (to happen, occur)
889. ofender (to offend)
890. morder (to bite)
891. moler (to grind, mill)
892. entretener (to entertain)
893. complacer (to please)
894. emerger (to emerge)
895. coser (to sew)
896. atener (to abide by, adhere)
897. prender (to catch, arrest, turn on)
898. encoger (to shrink)
899. prevalecer (to prevail)
900. trascender (to transcend)
901. atañer (to concern, pertain)
902. preceder (to precede)
903. recomponer (to recompose, mend)
904. yacer (to lie down)
905. verter (to pour, spill)
906. recaer (to relapse, fall again)
907. subyacer (to underlie)
908. presuponer (to presuppose, assume)
909. sustraer (to subtract, remove)
910. abstener (to abstain)
911. exceder (to exceed)
912. reaparecer (to reappear)
913. revolver (to stir, scramble)
914. abastecer (to supply, provide)
915. barrer (to sweep)
916. rehacer (to re-do)

List of IR Verbs
Regular verbs ending in -IR are slightly less common but very important. Here’s the full list.

917. existir (to exist)
918. permitir (to permit, allow)
919. vivir (to live)
920. ocurrir (to occur, happen)
921. cumplir (to fulfill, accomplish)
922. abrir (to open)
923. recibir (to receive)
924. constituir (to constitute)
925. escribir (to write)
926. referir (to refer)
927. decidir (to decide)
928. añadir (to add)
929. consistir (to consist of)
930. reducir (to reduce)
931. requerir (to require)
932. descubrir (to discover)
933. exigir (to demand)
934. subir (to go up, to climb, to upload)
935. definir (to define)
936. dirigir (to direct, manage)
937. cubrir (to cover)
938. sufrir (to suffer)
939. asumir (to assume, take on)
940. reunir (to gather, reunite)
941. insistir (to insist)
942. unir (to unite, join)
943. surgir (to arise, emerge)
944. combatir (to combat, fight)
945. asistir (to attend, assist)
946. discutir (to discuss, argue)
947. acudir (to go, attend)
948. recurrir (to resort to, recur)
949. compartir (to share)
950. destruir (to destroy)
951. sustituir (to substitute, replace)
952. contribuir (to contribute)
953. partir (to leave, divide)
954. admitir (to admit)
955. coincidir (to coincide, agree)
956. disminuir (to diminish, decrease)
957. transmitir (to transmit, broadcast)
958. describir (to describe)
959. percibir (to perceive)
960. confundir (to confuse)
961. sobrevivir (to survive)
962. prevenir (to prevent)
963. resistir (to resist)
964. residir (to reside, live)
965. presidir (to preside over, chair)
966. emitir (to emit, issue)
967. atribuir (to attribute)
968. invertir (to invest, invert)
969. sugerir (to suggest)
970. herir (to injure, hurt)
971. provenir (to originate, come from)
972. consumir (to consume)
973. reproducir (to reproduce, replicate)
974. perseguir (to pursue, chase)
975. dividir (to divide)
976. deducir (to deduce, infer)
977. concebir (to conceive, imagine)
978. hervir (to boil)
979. reconstruir (to reconstruct, rebuild)
980. interrumpir (to interrupt)
981. difundir (to spread, disseminate)
982. repartir (to distribute, hand out)
983. suprimir (to suppress, delete)
984. prescindir (to do without, dispense with)
985. proseguir (to continue, proceed)
986. prohibir (to prohibit, forbid)
987. regir (to govern, rule)
988. hundir (to sink)
989. distribuir (to distribute)
990. eludir (to elude, avoid)
991. aludir (to allude, refer)
992. resumir (to summarize)
993. suscribir (to subscribe)
994. batir (to beat, whisk)
995. exhibir (to exhibit, display)
996. concernir (to concern, affect)
997. persistir (to persist)
998. conferir (to confer, bestow)
999. asentir (to agree, assent)
1000. imprimir (to print)
1001. excluir (to exclude)
1002. transcurrir (to elapse, pass)
1003. debatir (to debate, discuss)
1004. predecir (to predict)
1005. inscribir (to enroll, register)
1006. convivir (to coexist, live together)
1007. reprimir (to repress, suppress)
1008. inducir (to induce, lead)
1009. dimitir (to resign)
1010. remitir (to remit, send)
1011. ingerir (to ingest, consume)
1012. invadir (to invade)
1013. sacudir (to shake)
1014. presumir (to presume, show off)
1015. lucir (to shine, look good)
1016. seducir (to seduce)
1017. revivir (to revive, relive)
1018. incidir (to influence, affect)
1019. diferir (to differ, defer)
1020. impartir (to impart, give)
1021. desmentir (to deny, refute)
1022. evadir (to evade, avoid)
1023. sumir (to plunge, sink)
1024. restringir (to restrict, limit)
1025. transferir (to transfer)
1026. concurrir (to concur, attend)
1027. relucir (to shine, sparkle)
1028. fundir (to melt, fuse)
1029. sumergir (to submerge, immerse)
1030. discurrir (to reflect, pass by)
1031. destituir (to dismiss, remove from office)
1032. incurrir (to incur, commit)
1033. subsistir (to subsist, survive)
1034. aplaudir (to applaud, clap)
1035. contradecir (to contradict)
1036. revertir (to revert)
1037. escurrir (to drain, drip)
1038. revestir (to cover, coat)
1039. expandir (to expand)
1040. fluir (to flow)
1041. discernir (to discern)
1042. fingir (to pretend, fake)
1043. suplir (to supply, replace)
1044. entreabrir (to half-open, open slightly)
1045. intuir (to intuit, sense)
1046. interferir (to interfere)
1047. inquirir (to inquire)
1048. persuadir (to persuade)
1049. nutrir (to nourish)
1050. sobresalir (to stand out, excel)
1051. confluir (to converge, flow together)
1052. abatir (to knock down, depress)